# -*- coding: utf-8 -*-
"""SCRIPT INSERT INTO (range)

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19C8YKN-QQJsCZ20_Cp6a0CFfz362SYQo
"""

for Guia in range(1639,1877):
  print('INSERT INTO TDFicha (Exercicio, Guia, Tributo, Contribuinte, Imovel, [Valor Original], [Valor Pago], Data, [Data de Cadastro], Automatico, DataPgtoDam) ')
  print('VALUES ("2021", ', end="")
  print(Guia, end="")
  print(', "10", "4133", "000000019LT413001", "50", "50", "27/12/2021", "27/12/2021", true, "27/12/2021");')